# Generated by Django 4.2.2 on 2023-06-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comentPost',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comentUser',
            new_name='commentUser',
        ),
    ]
